# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d01bf1570ba4d3037eba27f1fb8597139dd92038577356875035c80f2d0bf63f4c20fc20fea6cb0684f5ffabb613c33e202929778af09428d44d6248d46eb51f

test:
  secret_key_base: 06076ae63ee84fb778adad6d72a0682d56975c5865fc754c47380a6a1c34de59719fb15aa114cf920451e70fc981cebfb5ebd12cab831cf155284591cb9c2ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
